version: '3'
services:
  web:
    build: './'
    restart: 'always'
    depends_on:
      - 'db'
    ports:
      - '8080:8080'
    environment:
      - 'DB_HOST=mongodb://${DB_USERNAME}:${DB_PASSWORD}@db:27017/admin'
  db:
    image: 'mongo:4.2'
    restart: 'always'
    volumes:
      - '${DB_DATA_PATH}/www:/data/db'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}'
