name: Generate Cypress report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-test:
    name: Run on Chrome

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install cypress and verify
        working-directory: website
        run: |
          npm ci
          $(npm bin)/cypress verify

      - name: Start server
        working-directory: website
        run: npm run e2e:ci
          
      - name: Run Cypress tests
        working-directory: website
        run: npm run cypress:run-ci
        continue-on-error: true

      - name: Generate HTML report
        working-directory: website
        run: npm run cypress:report
        
      - name: Deploy report page to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/publicCypress
