name: Generate Cypress report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-test:
    name: Cypress Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install cypress and verify
        working-directory: website
        run: |
          npm ci
          $(npm bin)/cypress verify

      - name: Start server
        working-directory: website
        run: |
          cp sample.env .env
          docker-compose -f docker/development/docker-compose.yaml up -d

      - name: Wait for server
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:8080/'
          responseCode: '200,500'
          timeout: 60000
          interval: 10000 
          
      - name: Run Cypress tests
        working-directory: website
        run: npm run cypress:run-ci
        continue-on-error: false

      - name: Generate HTML report
        working-directory: website
        run: npm run cypress:report
        
      - name: Deploy report page to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/publicCypress

      - name: Get PR nr
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);

      - name: Print pull_request nr
        run: |
          echo "1. PR nr ${{github.event.number}}"
          echo "2. PR nr ${{github.event.issue.number}}"
          echo "$GITHUB_REF" | awk -F / '{print $3}'
          echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'
          echo $PULL_NUMBER
